### ISSUE TITLE
invitation reflinks meta

### ISSUE THREAD

**Issue by zeroone2numeral2** [zeroone2numeral2/bbr-staff-bot#49]
Todos:
- [ ] command to get the message with an inline button prompting the user to select another users with `switch_inline_query_chosen_chat` (also allow group chats?)
- [ ] inline mode should be supported. prompt the user to send their invitation link
- [ ] command to ban invitations from an user (if their link is used, warn the user that the invite link they used is not valid)
- [ ] `/ban` should also ban invitations from that user
- [ ] the log chat message should show a special field with the inviter

**Comment by zeroone2numeral2** [comment]
Maybe we can make it work in a way that an user's invite link can be used just once, and then it should be generated again
